rollerworks/search

src/Test/SearchIntegrationTestCase.php, tests/Rollerworks/Component/Search/Tests/Exporter/SearchConditionExporterTestCase.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/BirthdayTypeTest.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/ChoiceTypeTest.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/DateTimeTypeTest.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/IntegerTypeTest.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/MoneyTypeTest.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/NumberTypeTest.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/TextTypeTest.php, tests/Rollerworks/Component/Search/Tests/Extension/Core/Type/TimeTypeTest.php, tests/Rollerworks/Component/Search/Tests/Input/InputProcessorTestCase.php
There is a BC if you used the SearchIntegrationTestCase.
Instead of using the `$factory` property you now need to call `getFactory()` after you registered all the extensions and types!
=> refactor SearchIntegrationTestCase for easier usage

UPGRADE.md, spec/Rollerworks/Component/Search/FieldSetRegistrySpec.php, src/FieldSetRegistry.php, src/FieldSetRegistryInterface.php, src/SearchConditionSerializer.php, tests/Rollerworks/Component/Search/Tests/SearchConditionSerializerTest.php
This PR introduces a FieldSetRegistry for tracking FieldSets throughout the search system.
The main purpose for this is to simplify the SearchConditionSerializer class
which can be now ask for a FieldSet rather then requiring this to be passed explicitly.
Todo: **Update UPGRADE.md.**
=> Refactor SearchConditionSerializer to use a FieldSetRegistry

UPGRADE.md, src/AbstractFieldType.php, src/AbstractFieldTypeExtension.php, src/FieldTypeExtensionInterface.php, src/FieldTypeInterface.php, src/ResolvedFieldType.php
Using Field is unnecessary here as the FieldType can only
be used for a field. It makes the API a little cleaner.
=> rename buildFieldView() to buildView()

src/SearchFactory.php, src/SearchFactoryBuilder.php
The old compatibility layer for the JMS Metadata reader is removed as it makes no sense to keep this,
while there are already so many BC breaks.
=> SearchFactoryBuilder required the wrong interface

spec/FieldSetBuilderSpec.php, spec/SearchFactorySpec.php, src/Extension/Core/Type/FieldType.php, src/FieldSetBuilder.php, src/SearchFactory.php, src/SearchFactoryInterface.php, src/SearchField.php
This moves the configuring of field's model-reference to the options. The model reference is not actually mandatory but was introduced for Doctrine ORM and Metadata loading.
But currently they can't be used for options as the configureOptions method doesn't receive the FieldConfig and so (lazy) options that depend on this information are impossible as I want to do in: 
https://github.com/rollerworks/rollerworks-search-symfony-validator/issues/5
=> move configuring of model-reference to options

UPGRADE.md, composer.json, src/Extension/Core/Type/BirthdayType.php, src/Extension/Core/Type/ChoiceType.php, src/Extension/Core/Type/DateTimeType.php, src/Extension/Core/Type/DateType.php, src/Extension/Core/Type/FieldType.php, src/Extension/Core/Type/IntegerType.php, src/Extension/Core/Type/NumberType.php
|Q            |A          |
|---          |---        |
|Bug Fix?     |no         |
|New Feature? |no         |
|BC Breaks?   |yes (minor)|
|Deprecations?|no         |
|Fixed Tickets|Closes #88 |
|License      |MIT        |
This was actually very easy 😀  note that if you don't allow Symfony 2.8 components this will fail. But Symfony 2.3 is nearing End of live soon
=> Remove Symfony 2.3 BC layer

src/ValuesBag.php, tests/ValuesBagTest.php
The internalvalue was not extracted for getExcludedSimpleValues()
=> Fix ValuesBag::addExcludedValue() breaks new API

src/FieldConfigInterface.php, src/Input/FieldValuesFactory.php, src/SearchField.php, src/Value/Compare.php, src/Value/Range.php, src/Value/RequiresComparatorValueHolder.php, src/Value/ValuesBag.php, tests/Input/ArrayInputTest.php, tests/Input/FilterQueryInputTest.php, tests/Input/JsonInputTest.php, tests/Input/XmlInputTest.php, tests/SearchFieldTest.php
A value-holder implementing the RequiresComparatorValueHolder indicates a value Comparator
is required for the field configuration.
=> Add RequiresComparatorValueHolder to check config

composer.json, src/Extension/Core/DataTransformer/BaseNumberTransformer.php, src/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php, src/Extension/Core/DataTransformer/MoneyToStringTransformer.php, src/Extension/Core/DataTransformer/NumberToStringTransformer.php, src/Extension/Core/Model/MoneyValue.php, src/Extension/Core/Type/MoneyType.php, src/Extension/Core/ValueComparison/MoneyValueComparison.php, tests/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformerTest.php, tests/Extension/Core/DataTransformer/MoneyToStringTransformerTest.php, tests/Extension/Core/Type/MoneyTypeTest.php, tests/Extension/Core/ValueComparison/MoneyValueComparisonTest.php
The MoneyType and related DataTransformers now use the PhpMoney library for
handling money amounts.
- The precision (scale) and devisor options are removed as this is now handled by
the money library.
- MoneyValueComparison now allows to increase by cents or full amounts
- Some problems with space grouped money amounts are fixed (edge case)
- Only export currency when it was actually provided (feature)
Todo:
=> Fix MoneyType precision related problems

src/Exporter/StringQueryExporter.php, src/Input/StringQuery/Lexer.php, src/Input/StringQuery/QueryException.php, src/Input/StringQueryInput.php, tests/Exporter/StringQueryExporterTest.php, tests/Input/StringQueryInputTest.php
FilterQuery still carries the old name used when this library was still a Bundle,
but the name tells nothing. This library is about searching, not filtering.
I tried a number of names but string is the most descriptive.
=> Rename FilterQuery to StringQuery

doc/input/filter_query.rst
Field values are started with `:` not `=`
=> [Doc] Fix wrong example in FilterQuery syntax

src/Exception/UnsupportedFieldSetException.php, src/SearchCondition.php, tests/SearchConditionTest.php
The FieldSet holds a specific configuration of fields, which may not be supported everywhere.
To check if the FieldSet of a SearchCondition is supported in the context the `assertFieldSetName`
allows to check if the FieldSet is supported.
=> Add SearchCondition::assertFieldSetName

composer.json, src/LazyFieldSetRegistry.php, src/Loader/ClosureContainer.php, src/Loader/ConditionExporterLoader.php, src/Loader/InputProcessorLoader.php, src/Loader/ServiceNotFoundException.php, src/SearchFactoryBuilder.php, tests/LazyFieldSetRegistryTest.php, tests/Loader/ConditionExporterLoaderTest.php, tests/Loader/InputProcessorLoaderTest.php
Use the PSR-11 ContainerInterface for lazily loading dependencies (InputProcessors, ConditionExporters, FieldSet configurators), and easing framework integration.
The `LazyFieldSetRegistry` no longer accepts factories in constructor, use `LazyFieldSetRegistry::create()` instead.
=> Introduce better Lazy loading of dependencies

src/ConditionOptimizer/DuplicateRemover.php, src/ConditionOptimizer/RangeOptimizer.php, src/ConditionOptimizer/ValueSortCompare.php, src/ConditionOptimizer/ValuesToRange.php, src/Extension/Core/CoreExtension.php, src/Extension/Core/Type/BaseDateTimeType.php, src/Extension/Core/Type/BirthdayType.php, src/Extension/Core/Type/DateTimeType.php, src/Extension/Core/Type/DateType.php, src/Extension/Core/Type/IntegerType.php, src/Extension/Core/Type/MoneyType.php, src/Extension/Core/Type/NumberType.php, src/Extension/Core/Type/SearchFieldType.php, src/Extension/Core/Type/TimeType.php, src/Extension/Core/Type/TimestampType.php, src/Extension/Core/ValueComparator/BirthdayValueComparator.php, src/Extension/Core/ValueComparator/DateTimeValueValueComparator.php, src/Extension/Core/ValueComparator/DateValueComparator.php, src/Extension/Core/ValueComparator/MoneyValueComparator.php, src/Extension/Core/ValueComparator/NumberValueComparator.php, src/Extension/Core/ValueComparator/SimpleValueComparator.php, src/Field/FieldConfig.php, src/Field/SearchField.php, src/Input/FieldValuesFactory.php, tests/Extension/Core/ValueComparison/DateValueComparisonTest.php, tests/Extension/Core/ValueComparison/MoneyValueComparisonTest.php, tests/Input/FieldValuesFactoryTest.php, tests/SearchFieldTest.php
The ValueComparisonInterface was already renamed to ValueComparator but related classes, methods and variable were not. This pr makes them consistent again.
=> Rename ValueComparison to ValueComparator

src/Extension/LazyExtension.php, src/Loader/ClosureContainer.php, tests/LazyExtensionTest.php
Allow lazy loading types using a PSR-11 compatible container or Closures.
=> Add LazyExtension for loading types lazily

composer.json, src/Input/JsonInput.php, tests/Input/JsonInputTest.php
Remove the linting of Json input and use regular error checking instead. The Json linter is written in PHP which is slower then native C, secondly this level of error reporting doesn't provide any benefit as this input format is not something a user would generate by hand (unlike configuration files).
=> [Input] Remove Json linting to reduce deps

composer.json, src/Extension/Core/Type/MoneyType.php
The MoneyType uses the phpmoney library but not every installation uses the MoneyType, this makes the phpmoney library optional.
=> [CoreExtension] Make phpmoney lib optional

UPGRADE-2.0.md, phpstan.neon, src/Exporter/StringQueryExporter.php, src/Input/StringLexer.php, src/Test/SearchConditionExporterTestCase.php, src/Value/PatternMatch.php, tests/Exporter/ArrayExporterTest.php, tests/Exporter/JsonExporterTest.php, tests/Exporter/StringQueryExporterTest.php, tests/Exporter/XmlExporterTest.php, tests/Input/ArrayInputTest.php, tests/Input/InputProcessorTestCase.php, tests/Input/JsonInputTest.php, tests/Input/StringQueryInputTest.php, tests/Input/XmlInputTest.php
Remove support for Regex ValueMatch:
- This is not supported in Elastic Search, and would cause an inconsistency with other processors.
- Allowing Regexes without any form of validation opens the system to "Regular expression Denial of Service" attacks.
- YAGNI, most operations can be solved using begin/ends/contains matches.
=> Remove support for Regex ValueMatch

src/SearchCondition.php, src/SearchPreCondition.php, tests/SearchConditionTest.php
Related to https://github.com/rollerworks/search/issues/182
This reuses the SearchConditon model-format to compose a Condition that is only used for generating a pre-condition in the Query. This reuses the (root) SearchCondition's FieldSet as providing a separate FieldSet makes asserting a supported FieldSet more complicated. As an alternative some fields can be marked as internal/hidden to disallow usage by InputProcessors.
=> Allow to set a PreCondition for result limiting

lib/Elasticsearch/Extension/Conversion/DateTimeConversion.php, lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php
Bugfix.
When using FOS Elastica bundle, it will by default try to serialize like `2017-10-26T12:11:58+00:00`. This might produce problems with datetime formats when ingesting / querying.
This streamlines the formats used by default by Elasticsearch, FOS Elastica, us.
=> [Elasticsearch] Match datetime format with FOS Elastica defaults

composer.json, lib/ApiPlatform/Elasticsearch/Extension/SearchExtension.php, lib/ApiPlatform/Tests/Elasticsearch/Extension/SearchExtensionTest.php, lib/Elasticsearch/QueryConditionGenerator.php, lib/Symfony/SearchBundle/DependencyInjection/Compiler/ElasticaBundlePass.php, lib/Symfony/SearchBundle/DependencyInjection/Configuration.php, lib/Symfony/SearchBundle/DependencyInjection/RollerworksSearchExtension.php, lib/Symfony/SearchBundle/Resources/config/api_platform_elasticsearch.xml, lib/Symfony/SearchBundle/Resources/config/elasticsearch.xml, lib/Symfony/SearchBundle/RollerworksSearchBundle.php, lib/Symfony/SearchBundle/Tests/Functional/Application/AppKernel.php, lib/Symfony/SearchBundle/Tests/Functional/Application/config/api_platform.yml, lib/Symfony/SearchBundle/Tests/Functional/Application/config/default.yml, lib/Symfony/SearchBundle/Tests/Functional/Application/config/doctrine_dbal.yml, lib/Symfony/SearchBundle/Tests/Functional/Application/config/doctrine_orm.yml, lib/Symfony/SearchBundle/Tests/Functional/Application/config/elasticsearch.yml, lib/Symfony/SearchBundle/Tests/Functional/ElasticsearchTest.php
Porting https://github.com/rollerworks/search-api-platform/pull/8, https://github.com/rollerworks/RollerworksSearchBundle/pull/37 to new mono-repo.
Closes #179.
=> Integrate existing Elasticsearch support to Symfony, API Platform

.gitignore, .travis.yml, Makefile, composer.json, docker-compose.yaml, docker/Dockerfile, docker/Dockerfile-qa, lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php, travis/mysql.travis.xml, travis/pgsql.travis.xml
This makes the tests less dependent on the developer’s system. and FINALLY! Fixes the ICU versioning problem.
Note: this is a proof of concept, I am open to any suggestions 👍
=> Run tests in isolation (using Docker)

lib/Elasticsearch/QueryConditionGenerator.php, lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php
Get mappings missing for pattern matchers.
Note: this is exactly the same as #197, but my app wasn't picking up my fork to install, thought the branch name was tripping Composer up. Turns out it was #199.
=> [Elasticsearch] Fix getMappings() for pattern matcher and nested groups

composer.json
| Fixed tickets | Fixes #199
Allow to install RollerworksSearch monolith as it's own package for easier development testing.
=> Re-add composer.json root-package name

lib/ApiPlatform/composer.json, lib/Elasticsearch/composer.json, lib/Processor/composer.json
Update branch-aliases to 2.0-dev.
All split packages will have the same version, and therefor need a correct and matching branch-alias.
**You will need to update your composer constraints to use the new 2.0 constraint. But in the future upgrading will be much easier 👍**
=> Prepare for monolith release

UPGRADE-2.0.md, lib/ApiPlatform/EventListener/SearchConditionListener.php, lib/ApiPlatform/SearchConditionEvent.php, lib/ApiPlatform/Tests/EventListener/SearchConditionListenerTest.php, lib/Symfony/SearchBundle/Resources/config/api_platform.xml
| Fixed tickets | #182
| Doc PR        | pending
The SearchConditionListener dispatches an event to allow setting a pre-condition for QueryGenerator’s.
First a specific event is dispatched for the resource-class, and then a ‘generic’ event to allow for ease of listening _and_ enforcing ‘global’ defaults.
=> [ApiPlatform] Allow to set a pre-condition

lib/Doctrine/Dbal/CachedConditionGenerator.php, lib/Doctrine/Dbal/Tests/CachedConditionGeneratorTest.php, lib/Doctrine/Orm/CachedDqlConditionGenerator.php, lib/Doctrine/Orm/CachedNativeQueryConditionGenerator.php, lib/Doctrine/Orm/Tests/CachedDqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/CachedNativeQueryConditionGeneratorTest.php
| Doc PR        | n/a
The Doctrine DBAL/ORM Condition Caches did not include the pre-condition when computing the cache-key.
The PreCondition is part of the generated Query but the cache key doesn't change for a different PreCondition. If a non-restricting PreCondition was used before, the second cache hit will use this, ignoring the PreCondition with restrictions!
In practice leading to an information disclosure.
=> [Doctrine] Fix Cache key ignoring precondition

lib/ApiPlatform/EventListener/SearchConditionListener.php, lib/ApiPlatform/Processor/ApiSearchProcessor.php, lib/ApiPlatform/Tests/EventListener/SearchConditionListenerTest.php, lib/ApiPlatform/Tests/Processor/ApiSearchProcessorTest.php, lib/Core/Exporter/NormStringQueryExporter.php, lib/Core/Exporter/StringExporter.php, lib/Core/Input/NormStringQueryInput.php, lib/Core/Input/StringInput.php, lib/Core/Input/StringQueryInput.php, lib/Core/Loader/ConditionExporterLoader.php, lib/Core/Loader/InputProcessorLoader.php, lib/Core/Tests/Exporter/NormStringQueryExporterTest.php, lib/Core/Tests/Input/NormStringQueryInputTest.php, lib/Core/Tests/Loader/ConditionExporterLoaderTest.php, lib/Core/Tests/Loader/InputProcessorLoaderTest.php, lib/Processor/AbstractSearchProcessor.php, lib/Symfony/SearchBundle/Resources/config/condition_exporter.xml, lib/Symfony/SearchBundle/Resources/config/input_processor.xml, lib/Symfony/SearchBundle/Tests/Functional/ApiPlatformTest.php, phpstan.neon
| Fixed tickets | Closes #176 
| Doc PR        | pending
This is a proof of RFC to allow a normalized value-format for the StringQuery syntax.
ApiPlatform integration is currently pending but I wonder what is the best way do this?
_In any siltation the NormStringQuery must be encoded for usage in the URL (SearchCode as done in the SearchProcessor component is properly not going to work as this requires a POST. Otherwise there are to many details in the client side)._
1. Allow both Array and NormStringQuery
2. Use only NormStringQuery
=> [Input] Introduce NormStringQuery for processing normalizev value in StringQuery

lib/Core/Exporter/AbstractExporter.php, lib/Core/Exporter/NormStringQueryExporter.php, lib/Core/Exporter/StringExporter.php, lib/Core/Extension/Core/Type/MoneyType.php, lib/Core/Extension/Core/Type/SearchFieldType.php, lib/Core/Input/NormStringQueryInput.php, lib/Core/Input/StringInput.php, lib/Core/Input/StringLexer.php, lib/Core/Input/StringQueryInput.php, lib/Core/Test/SearchConditionExporterTestCase.php, lib/Core/Tests/Exporter/NormStringQueryExporterTest.php, lib/Core/Tests/Exporter/StringQueryExporterTest.php, lib/Core/Tests/Extension/Core/Type/MoneyTypeTest.php, lib/Core/Tests/Input/NormStringQueryInputTest.php, lib/Core/Tests/Input/StringQueryInputTest.php
| Fixed tickets | #185 
This allows to use a custom Lexer operation for field values in StringInput (`NormStringQueryInput` and `StringQueryInput`).
To use this new feature, the FieldConfiguration (FieldType) must configure (set) a lexical callback (Closure) which is called whenever a value-part is "analyzed" (being matched). That's it.
In practice you set eg. the `norm_string_query.value_lexer` option (and/or `string_query.value_lexer` respectively) with the following Closure:
```php
function (StringLexer $lexer): string {
$result = $lexer->expects('(');
$result .= …
```
=> [Core] Allow custom value Lexers for StringInput

lib/ApiPlatform/Processor/ApiSearchProcessor.php, lib/ApiPlatform/Tests/Processor/ApiSearchProcessorTest.php, phpstan.neon
| Fixed tickets | Closes #214
| Doc PR        | rollerworks/search-docs#... 
If the input is an array use the ArrayInput processor otherwise a string is expected for norm_string_query. The (default) search-format is silently ignored.
This makes the usage of API-Platform SearchProcessor easier and allows for using array by a client-side (either React/Angular, etc) or a Normalized StringQuery for communicating by 3rd party client.
Related to https://github.com/rollerworks/search/pull/202#issuecomment-350550520
=> [Api-platform] Automatically detect search-format

lib/ApiPlatform/Processor/ApiSearchProcessor.php, lib/ApiPlatform/Tests/Processor/ApiSearchProcessorTest.php
| Fixed tickets | #216 
The ApiSearchProcessor now always ensures a SearchCondition is set, even the condition is empty.
Which allows to set a pre-condition, when there is no actual SearchCondition.
Only in the case of a format error or validation constraint violation the SearchCondition is empty, but this is already handled by the Symfony API-Platform ExceptionHandler.
=> [ApiPlatform] Ensure a SearchCondition is present

lib/ApiPlatform/EventListener/SearchConditionListener.php, lib/ApiPlatform/Tests/EventListener/SearchConditionListenerTest.php, phpunit.xml.dist
| Deprecations? | yes
Using an ArrayInput is extreme verbose and can be easier solved using a JSON string, the SearchConditionListener automatically detects if a JSON string is provided, and expects the string_norm_query otherwise.
=> [ApiPlatform] Deprecate support for ArrayInput

lib/ApiPlatform/SearchConditionEvent.php, lib/Core/SearchCondition.php, lib/Core/SearchPrimaryCondition.php, lib/Core/Tests/SearchConditionTest.php, lib/Doctrine/Dbal/CachedConditionGenerator.php, lib/Doctrine/Dbal/Query/QueryGenerator.php, lib/Doctrine/Dbal/Tests/CachedConditionGeneratorTest.php, lib/Doctrine/Dbal/Tests/Functional/SqlConditionGeneratorResultsTest.php, lib/Doctrine/Dbal/Tests/SqlConditionGeneratorTest.php, lib/Doctrine/Orm/CachedDqlConditionGenerator.php, lib/Doctrine/Orm/CachedNativeQueryConditionGenerator.php, lib/Doctrine/Orm/Tests/CachedDqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/CachedNativeQueryConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/ConditionGeneratorResultsTestCase.php, lib/Doctrine/Orm/Tests/DqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/NativeQueryConditionGeneratorTest.php, lib/Elasticsearch/QueryConditionGenerator.php, lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php
The implementation for this functionality was introduced rather rapid without a good consideration for a proper name. PrimaryCondition describes exactly what this functionality is about it, it should always be applied (even if the user provided search condition is empty).
=> Rename PreConditon to PrimaryCondition

lib/ApiPlatform/Tests/Mock/FieldSetStub.php, lib/Core/Exporter/JsonExporter.php, lib/Core/Exporter/StringExporter.php, lib/Core/Field/SearchField.php, lib/Core/FieldSet.php, lib/Core/GenericFieldSet.php, lib/Core/Input/JsonInput.php, lib/Core/Input/NormStringQueryInput.php, lib/Core/Input/StringLexer.php, lib/Core/Input/StringQueryInput.php, lib/Core/Test/SearchConditionExporterTestCase.php, lib/Core/Tests/Exporter/JsonExporterTest.php, lib/Core/Tests/Exporter/NormStringQueryExporterTest.php, lib/Core/Tests/Exporter/StringQueryExporterTest.php, lib/Core/Tests/Input/InputProcessorTestCase.php, lib/Core/Tests/Input/JsonInputTest.php, lib/Core/Tests/Input/StringQueryInputTest.php, lib/Core/Tests/Mock/FieldSetStub.php
| Fixed tickets | #219
A field name accepts a single underscore prefix to indicate it’s private, eg. `_id`.
There is no BC break here as field-names did not accept this format before.
Private fields can only be used in a PrimaryCondition and are simple ignored for user-input.
=> Add support for private fields

UPGRADE-2.0.md, lib/Core/Input/ProcessorConfig.php, lib/Core/Tests/Input/InputProcessorTestCase.php
Allowing  1000 values per field or allowing a maximum nesting level of a 100?
This reduces the Processor default values to more sensible values, to prevent DoS attacks.
=> Reduce the default allowed maximum values

lib/Core/SearchCondition.php, lib/Core/Tests/SearchConditionTest.php
| Fixed tickets | #216 
BC break only if one overwrites the `Rollerworks\Component\Search\SearchCondition::setPrimaryCondition` method in a child class.
Closes #216
=> [Core] Allow to unset the PrimaryCondition

lib/ApiPlatform/Elasticsearch/Extension/SearchExtension.php, lib/ApiPlatform/Tests/Elasticsearch/Extension/SearchExtensionTest.php, lib/Core/ParameterBag.php, lib/Elasticsearch/CachedConditionGenerator.php, lib/Elasticsearch/ConditionGenerator.php, lib/Elasticsearch/ElasticsearchFactory.php, lib/Elasticsearch/FieldMapping.php, lib/Elasticsearch/QueryConditionGenerator.php, lib/Elasticsearch/Tests/Functional/ConditionGeneratorResultsTest.php, lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php, lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php, lib/Symfony/SearchBundle/Resources/config/elasticsearch.xml, lib/Symfony/SearchBundle/Resources/config/services.xml
| Fixed tickets | #249 
Closes #249. Solves cases 1) and 2) from there. Case 3) is handled by decorating the factory, all use cases work well in my app.
=> [Elasticsearch] contextual support

lib/ApiPlatform/Elasticsearch/Extension/SearchExtension.php, lib/ApiPlatform/Tests/Elasticsearch/Extension/SearchExtensionTest.php, lib/Elasticsearch/CachedConditionGenerator.php, lib/Elasticsearch/ConditionGenerator.php, lib/Elasticsearch/FieldMapping.php, lib/Elasticsearch/QueryConditionGenerator.php, lib/Elasticsearch/QueryPreparationHints.php, lib/Elasticsearch/Tests/Functional/ConditionGeneratorResultsTest.php, lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php, lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php
| Fixed tickets | #241 
Based on #255, that must be merged first.
TODO:
=> [Elasticsearch] order-by support

lib/Elasticsearch/QueryConditionGenerator.php, lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php, lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php
| Fixed tickets | #270 
As I don't know elasticasearch internals good enough I'm not sure about other possible use cases besides "inner_hits". This option has to be set for nested/joined field conditionally (when field is really used in the query) and I can only solve it dirty way after generating of query...
I was thinking that we actually need to distinguish field options from conditions options and proper method signature could be:
```php
public function registerField(string $fieldName, string $property, array $conditions = [], array $conditionOptions = [], array $options = [])
{
}
``` …
=> [Elasticsearch] pass custom field options even if no condition is set

lib/Core/Input/ProcessorConfig.php, lib/Core/Input/StringInput.php, lib/Core/Input/StringLexer.php, lib/Core/Tests/Input/InputProcessorTestCase.php, lib/Core/Tests/Input/StringQueryInputTest.php
| Fixed tickets | Closes #230 
Aka "search anything", if no field name is specified this uses the default configured field.
Additionally we might add support for a default operator (or type in our case) in the future.
Secondly only StringInput has support for this now.
=> [Core] Add support for unbound values in StringInput

lib/Doctrine/Orm/CachedDqlConditionGenerator.php, lib/Doctrine/Orm/CachedNativeQueryConditionGenerator.php, lib/Doctrine/Orm/Tests/CachedDqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/CachedNativeQueryConditionGeneratorTest.php
Calling `getWhereClause()` with a prepend value stored the the prepend value within the cache, while only the actual where-clause must be stored.
=> [Doctrine] Fix cache storing prepend with cache

.github/workflows/ci.yaml, UPGRADE-2.0.md, composer.json, lib/ApiPlatform/composer.json, lib/Core/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php, lib/Core/Extension/Core/DataTransformer/NumberToLocalizedStringTransformer.php, lib/Core/ParameterBag.php, lib/Core/composer.json, lib/Doctrine/Dbal/composer.json, lib/Doctrine/Orm/composer.json, lib/Elasticsearch/composer.json, lib/Symfony/SearchBundle/composer.json, lib/Symfony/Validator/composer.json
* Add support PHP 8 and, and bump minimum version to PHP 7.2 (which is still rather old).
* All Symfony versions below 4.4 were already not tested in detail, but I feel it's better to drop support for these older versions completely.
=> PHP 8 compatibility and dropping support for Symfony < 4.4

Makefile, UPGRADE-2.0.md, docs/integration/doctrine/orm.rst, lib/ApiPlatform/Doctrine/Orm/Extension/SearchExtension.php, lib/ApiPlatform/Tests/Doctrine/Orm/Extension/SearchExtensionTest.php, lib/ApiPlatform/composer.json, lib/Core/Extension/Core/DataTransformer/MultiTypeDataTransformer.php, lib/Core/SearchConditionBuilder.php, lib/Core/SearchOrder.php, lib/Doctrine/Dbal/Tests/DbalTestCase.php, lib/Doctrine/Dbal/Tests/Functional/FunctionalDbalTestCase.php, lib/Doctrine/Orm/CachedDqlConditionGenerator.php, lib/Doctrine/Orm/ConditionGenerator.php, lib/Doctrine/Orm/DoctrineOrmFactory.php, lib/Doctrine/Orm/DqlConditionGenerator.php, lib/Doctrine/Orm/QueryBuilderConditionGenerator.php, lib/Doctrine/Orm/Tests/CachedDqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/ConditionGeneratorResultsTestCase.php, lib/Doctrine/Orm/Tests/DoctrineOrmFactoryTest.php, lib/Doctrine/Orm/Tests/DqlConditionGeneratorResultsTest.php, lib/Doctrine/Orm/Tests/DqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/OrmTestCase.php, phpstan.neon, phpunit.xml.dist
| Tickets       | Fix #289, related to #290
To make ordering with Doctrine ORM work you need need to pass a QueryBuilder now, using a "loose" Query object is no longer possible. It's still possible to generate the where-clause, but it's not officially documented.
=> [Doctrine ORM] Add support for ordering

lib/Core/Tests/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformerTest.php, lib/Core/Tests/Extension/Core/DataTransformer/LocalizedBirthdayTransformerTest.php, lib/Core/Tests/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformerTest.php, lib/Core/Tests/Extension/Core/DataTransformer/NumberToLocalizedStringTransformerTest.php, lib/Core/Tests/Extension/Core/Type/CountryTypeTest.php, lib/Core/Tests/Extension/Core/Type/CurrencyTypeTest.php, lib/Core/Tests/Extension/Core/Type/LanguageTypeTest.php, lib/Core/Tests/Extension/Core/Type/LocaleTypeTest.php, lib/Core/Tests/Extension/Core/Type/TimezoneTypeTest.php
For some reason the second argument was false while this was actually never supported. As Symfony started enforcing proper types this misuse started to appear now.
=> [Core] Fix failing tests with IntlTestHelper

.github/workflows/ci.yaml, composer.json, lib/Core/SearchConditionBuilder.php, lib/Core/Value/ValuesBag.php, lib/Core/Value/ValuesGroup.php, lib/Core/ValuesBagBuilder.php, lib/Doctrine/Dbal/Query/QueryField.php, lib/Doctrine/Dbal/Tests/CachedConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/CachedDqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/DqlConditionGeneratorTest.php, lib/Symfony/SearchBundle/Tests/SearchConditionBuilderTest.php
- Check if a field is registered rather than silently failing
- Add more PHPDoc with explanations
- Add tests for SearchConditionBuilder
Note: this removes the `$forceNew` parameter for the `field` method that was already deprecated previously, wasn't removed in the announced version yet.
=> [Core] Make SearchConditionBuilder easier to use

.github/workflows/ci.yaml, Makefile, UPGRADE-2.0.md, docker/Dockerfile, docs/integration/doctrine/dbal.rst, lib/Doctrine/Dbal/AbstractCachedConditionGenerator.php, lib/Doctrine/Dbal/CachedConditionGenerator.php, lib/Doctrine/Dbal/ConditionGenerator.php, lib/Doctrine/Dbal/DoctrineDbalFactory.php, lib/Doctrine/Dbal/FieldConfigurationSet.php, lib/Doctrine/Dbal/Query/QueryGenerator.php, lib/Doctrine/Dbal/SqlConditionGenerator.php, lib/Doctrine/Dbal/Test/QueryBuilderAssertion.php, lib/Doctrine/Dbal/Tests/CachedConditionGeneratorTest.php, lib/Doctrine/Dbal/Tests/DoctrineDbalFactoryTest.php, lib/Doctrine/Dbal/Tests/Functional/Extension/Conversion/AgeConversionTest.php, lib/Doctrine/Dbal/Tests/Functional/Extension/Conversion/ChildCountTypeTest.php, lib/Doctrine/Dbal/Tests/Functional/Extension/Conversion/MoneyValueConversionTest.php, lib/Doctrine/Dbal/Tests/Functional/FunctionalDbalTestCase.php, lib/Doctrine/Dbal/Tests/Functional/SqlConditionGeneratorResultsTest.php, lib/Doctrine/Dbal/Tests/Functional/SqlConditionGeneratorTest.php, lib/Doctrine/Dbal/Tests/SqlConditionGeneratorTest.php, lib/Doctrine/Orm/CachedDqlConditionGenerator.php, lib/Doctrine/Orm/Tests/CachedDqlConditionGeneratorTest.php, lib/Doctrine/Orm/composer.json
| Tickets       | Closes #290 
Require a QueryBuilder is used for Doctrine DBAL, which also ensures ordering is applied correctly.
Due too some technical details it's no longer possible to retrieve the generated where-condition, this is now made all internal.
However I do plan to make a few test-helper classes to make testing of conversions much easier.
=> [DBAL] Require QueryBuilder for generating

.github/workflows/ci.yaml, lib/Core/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php, lib/Core/Extension/Core/DataTransformer/DateTimeToStringTransformer.php, lib/Core/Extension/Core/Type/DateTimeType.php, lib/Core/Tests/Extension/Core/Type/DateTimeTypeTest.php
| Tickets       |  
ICU data changed and was breaking the tests and parsing of localized date(time).
=> Fix tests for PHP 8.2

lib/Core/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php, lib/Core/Test/FieldTransformationAssertion.php, lib/Core/Tests/Extension/Core/Type/DateTimeTypeTest.php, lib/Core/Tests/Extension/Core/Type/DateTypeTest.php
The `FieldTransformationAssertion` used the `transform()` method, while `reverseTransform()` must be used foruser-input
As a small bonus isn't now possible to specify which transformation-failed exception is expected.
=> [Core] Fix FieldTransformationAssertion wrong tranformation method

lib/Core/Exporter/JsonExporter.php, lib/Core/Exporter/StringExporter.php, lib/Core/Extension/Core/DataTransformer/OrderToLocalizedTransformer.php, lib/Core/Field/OrderFieldType.php, lib/Core/Input/JsonInput.php, lib/Core/Input/OrderStructureBuilder.php, lib/Core/Input/ProcessorConfig.php, lib/Core/Input/StringQueryInput.php, lib/Core/Resources/translations/validators.en.xlf, lib/Core/Resources/translations/validators.nl.xlf, lib/Core/Test/SearchConditionExporterTestCase.php, lib/Core/Tests/Exporter/JsonExporterTest.php, lib/Core/Tests/Exporter/NormStringQueryExporterTest.php, lib/Core/Tests/Exporter/StringQueryExporterTest.php, lib/Core/Tests/Field/OrderFieldTest.php, lib/Core/Tests/Field/OrderFieldTypeTest.php, lib/Core/Tests/Input/InputProcessorTestCase.php, phpstan-baseline.neon
- Ordering direction was not included in exported conditions
- String (view format) didn't support localized labels
- The OrderStructureBuilder didn't use the correct transformer when changing fields; as this is configurable per field
**IMPORTANT**
```PHP
$fieldSet->add('@date', OrderFieldType::class, ['case' => OrderTransformer::CASE_LOWERCASE, 'alias' => ['up' => 'ASC', 'down' => 'DESC'], 'default' => 'down']);
$fieldSet->add('@id', OrderFieldType::class, ['default' => 'ASC']);
```
Previously the `@id` would contain the same transformer as the `@date` field (due to a bug in the `OrderStructureBuilder`), but this is …
=> [Core] Fix ordering not properly handled

lib/Core/Exception/OrderStructureException.php, lib/Core/Input/NormStringQueryInput.php, lib/Core/Input/OrderStructureBuilder.php, lib/Core/Input/StringInput.php, lib/Core/Test/SearchIntegrationTestCase.php, lib/Core/Tests/Input/InputProcessorTestCase.php, lib/Core/Tests/Input/NormStringQueryInputTest.php, lib/Core/Tests/Input/StringQueryInputTest.php
- Order field allowed invalid value types
- Order field in group did not error
- NormStringQueryInput didn't use the correct structure builder
- Use proper error messages (translations will be added later)
Note: Translations will be added later, there are some other problems with this which need to be resolved separate.
=> [Core] Fix order-clause with in StringInput

lib/Doctrine/Dbal/QueryPlatform/AbstractQueryPlatform.php, lib/Doctrine/Dbal/Tests/SqlConditionGeneratorTest.php, lib/Doctrine/Orm/QueryPlatform/DqlQueryPlatform.php, lib/Doctrine/Orm/Tests/ConditionGeneratorResultsTestCase.php, lib/Doctrine/Orm/Tests/DqlConditionGeneratorTest.php, lib/Doctrine/Orm/Tests/OrmTestCase.php
The pattern matches for BEGINS with, and ENDS with were reversed. 
Add some tests to ensure correct behavior.
=> [Doctrine] Fix wrong query for pattern matches

lib/Core/Exporter/StringExporter.php, lib/Core/Exporter/StringQueryExporter.php, lib/Core/Test/SearchConditionExporterTestCase.php, lib/Core/Tests/Exporter/StringQueryExporterTest.php
| Tickets       | Related to #310
When the root `ValuesGroup` of the condition is a logical `OR`, with values, *and* the condition has order fields, the exporter would place the order fields prior to the root-group logical, which produces a syntax error.
"A group logical operator can only be used at the start of the input or before a group opening"
=> [Core] Fix wrong exported StringQuery with order

lib/Core/Input/StringLexer.php, lib/Core/Tests/Input/StringLexerTest.php, lib/Core/Tests/Input/StringQueryInputTest.php
The error message would inform the character position in relation to the whole input, but not the col relative to the line the error was encountered.
And addition this also fixes a bug where the snapshot of char, lineno, and cursor postion weren't reset before parsing.
=> [Core] Fix wrong col pos in StringLexer exception

lib/Symfony/SearchBundle/DependencyInjection/RollerworksSearchExtension.php
The the actual InputValidator class, and just the Symfony validator component
=> [SearchBundle] Enable validator when class the exists, instead of only the Symfony validator component

UPGRADE-2.0.md, docs/integration/symfony_validator.rst, lib/Symfony/Validator/InputValidator.php, lib/Symfony/Validator/Tests/InputValidatorTest.php, lib/Symfony/Validator/Type/FieldTypeValidatorExtension.php
Don't validate PatternMatch by default, use a separate constraints option as a PatternMatch is cannot use full values for constraints.
_For a field that expects an email it's not possible to use a PatternMatch with a constraint that enforces a valid email address._
=> [SF Validator] Handle PatternMatch separate

docs/integration/symfony_bundle.rst, lib/Core/Exporter/StringQueryExporter.php, lib/Core/Extension/Core/Type/SearchFieldType.php, lib/Core/Field/OrderFieldType.php, lib/Core/Input/StringQueryInput.php, lib/Symfony/SearchBundle/Resources/config/translator_alias_resolver.xml, lib/Symfony/SearchBundle/TranslatorBasedAliasResolver.php, lib/Symfony/SearchBundle/Type/TranslatableFieldTypeExtension.php, lib/Symfony/SearchBundle/Type/TranslatableOrderFieldTypeExtension.php
The 'field' option wasn't defined so it was never possible to even use a label for localized input (in StringQuery).
Secondly the labels can now be translated using a TranslatableInterface value (for the Symfony bundle).
=> Fix Field label configuration

lib/Core/Exception/GroupsNestingException.php, lib/Core/Exception/GroupsOverflowException.php, lib/Core/Input/ConditionStructureBuilder.php, lib/Core/Resources/translations/RollerworksSearch.en.xlf, lib/Core/Resources/translations/RollerworksSearch.nl.xlf, lib/Core/Resources/translations/validators.en.xlf, lib/Core/Resources/translations/validators.nl.xlf, lib/Core/Tests/Input/JsonInputTest.php, lib/Core/Tests/Input/StringQueryInputTest.php
- Fix wrong message-id
- Wrong domain for groups count overflow
- Missing error-path for groups count overflow (the message changed to be pointed to the exact position, so it needs this proper path)
=> Fix wrong message-id and error-path for groups

lib/Symfony/SearchBundle/Tests/TranslatorBasedAliasResolverTest.php, lib/Symfony/SearchBundle/TranslatorBasedAliasResolver.php
| New feature?  |yes
| BC breaks?    | yes/no
When the field is an order field but the translated label doesn't begin with an-`@` prepend the `@`-sign.
=> [SFBundle] Easier translation of order-field

lib/Doctrine/Orm/FieldConfigBuilder.php, lib/Doctrine/Orm/OrmQueryField.php, lib/Doctrine/Orm/Tests/FieldConfigBuilderTest.php
All information was already available except for the entity, while some conversions might read additional mapping info from an entity.
_In @Lifthill I have a specific conversion which requires the entity class._
=> [Doctrine] Add the Entity to OrmQueryField

lib/Doctrine/Dbal/Extension/Conversion/AgeDateConversion.php, lib/Doctrine/Dbal/Tests/SqlConditionGeneratorTest.php, lib/Doctrine/Orm/Extension/Conversion/AgeDateConversion.php, lib/Doctrine/Orm/Extension/Conversion/DateIntervalConversion.php
Passing a Type object for parameter references is deprecated, but was still used in our own code base.
_This have been part of BETA7 but was missed by me._
=> [Doctrine] Fix deprecations in internal code

lib/Core/Exception/TransformationFailedException.php, lib/Core/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php, lib/Core/Input/ErrorPathTranslator.php, lib/Core/Test/FieldTransformationAssertion.php, lib/Core/Tests/Extension/Core/DataTransformer/LocalizedBirthdayTransformerTest.php, lib/Core/Tests/Extension/Core/Type/DateTimeTypeTest.php, lib/Core/Tests/Extension/Core/Type/IntegerTypeTest.php, lib/Core/Tests/Extension/Core/Type/NumberTypeTest.php, lib/Core/Tests/GenericFieldSetTest.php, lib/Doctrine/Dbal/ColumnConversion.php, lib/Doctrine/Dbal/ValueConversion.php, lib/Doctrine/Orm/ColumnConversion.php, lib/Doctrine/Orm/ValueConversion.php, phpstan-baseline.neon
The ICU data changed that dates now expect a comma, (which I don't remember even using in the NL_NL locale).
But as this isn't common we allow date times without comma's.
And the 'Ar(abic)' locale was changed to `ar_BH` to ensure Arabic numerals, 'ar' isn't an official locale (but a language).
=> Fix broken tests
