.travis.yml
composer.json

bump minimum version requirements in composer.json

---

src/Exporter/AbstractExporter.php
tests/Rollerworks/Component/Search/Tests/Exporter/ArrayExporterTest.php
tests/Rollerworks/Component/Search/Tests/Exporter/FilterQueryExporterTest.php
tests/Rollerworks/Component/Search/Tests/Exporter/JsonExporterTest.php
tests/Rollerworks/Component/Search/Tests/Exporter/SearchConditionExporterTestCase.php
tests/Rollerworks/Component/Search/Tests/Exporter/XmlExporterTest.php

[Exporter] fix field label resolving

---

src/Input/FilterQuery/QueryException.php
src/Input/FilterQueryInput.php
src/Resources/translations/messages.en.xlf
src/Resources/translations/messages.nl.xlf
tests/Rollerworks/Component/Search/Tests/Input/FilterQueryInputTest.php

|Fixed Tickets| #10  |
closes #10

provide more information for QueryException

---

UPGRADE.md
spec/ResolvedFieldTypeSpec.php
src/AbstractFieldType.php
src/AbstractFieldTypeExtension.php
src/Extension/Core/Type/BirthdayType.php
src/Extension/Core/Type/ChoiceType.php
src/Extension/Core/Type/CountryType.php
src/Extension/Core/Type/CurrencyType.php
src/Extension/Core/Type/DateTimeType.php
src/Extension/Core/Type/DateType.php
src/Extension/Core/Type/FieldType.php
src/Extension/Core/Type/IntegerType.php
src/Extension/Core/Type/LanguageType.php
src/Extension/Core/Type/LocaleType.php
src/Extension/Core/Type/MoneyType.php
src/Extension/Core/Type/NumberType.php
src/Extension/Core/Type/TimeType.php
src/Extension/Core/Type/TimezoneType.php
src/FieldTypeExtensionInterface.php
src/FieldTypeInterface.php
src/ResolvedFieldType.php
src/ResolvedFieldTypeInterface.php

|Fixed Tickets|#48|
closes #48

Change Field type options handling

---

spec/FieldLabelResolver/ChainFieldLabelResolverSpec.php
src/FieldAliasResolver/ChainFieldAliasResolver.php
src/FieldLabelResolver/ChainFieldLabelResolver.php
src/FieldLabelResolver/NoopLabelResolver.php

add some FieldLabel resolvers

---

src/Exporter/AbstractExporter.php
src/Exporter/ArrayExporter.php
src/Exporter/FilterQueryExporter.php
src/Exporter/JsonExporter.php
src/Exporter/XmlExporter.php
src/Input/ArrayInput.php
src/Input/XmlInput.php
src/ValuesGroup.php
tests/Exporter/ArrayExporterTest.php
tests/Exporter/FilterQueryExporterTest.php
tests/Exporter/JsonExporterTest.php
tests/Exporter/SearchConditionExporterTestCase.php
tests/Exporter/XmlExporterTest.php
tests/Input/XmlInputTest.php

[Input] refactor internal logic to reduce complexity

---

src/Extension/Core/Type/BirthdayType.php
src/Extension/Core/Type/ChoiceType.php
src/Extension/Core/Type/DateTimeType.php
src/Extension/Core/Type/DateType.php
src/Extension/Core/Type/IntegerType.php
src/Extension/Core/Type/MoneyType.php
src/Extension/Core/Type/NumberType.php
src/Extension/Core/Type/TimeType.php
src/FieldConfigInterface.php
src/SearchField.php
src/Test/FieldTypeTestCase.php
tests/Extension/Core/Type/BirthdayTypeTest.php
tests/Extension/Core/Type/DateTimeTypeTest.php
tests/Extension/Core/Type/IntegerTypeTest.php
tests/Extension/Core/Type/MoneyTypeTest.php
tests/Extension/Core/Type/NumberTypeTest.php
tests/Extension/Core/Type/TimeTypeTest.php

Fix FieldTypes view for form rendering

---

spec/ValuesGroupSpec.php
src/ValuesGroup.php

fix ValuesGroup::getGroup()

---

src/Exception/FieldRequiredException.php
src/Exception/GroupsNestingException.php
src/Exception/GroupsOverflowException.php
src/Exception/InvalidSearchConditionException.php
src/Exception/UnknownFieldException.php
src/Exception/UnsupportedValueTypeException.php
src/Exception/ValuesOverflowException.php

input exceptions extend InputProcessorException

---

src/Input/ArrayInput.php
src/Input/FilterQueryInput.php
src/Input/XmlInput.php
tests/Input/ArrayInputTest.php
tests/Input/FilterQueryInputTest.php
tests/Input/InputProcessorTestCase.php
tests/Input/JsonInputTest.php
tests/Input/XmlInputTest.php

A SearchCondition with nested groups was not checked for errors.
Tests need to be updated prevent regressions.

fix nested errors did not throw Exception

---

src/Input/FilterQuery/Lexer.php
src/Input/FilterQuery/QueryException.php
src/Input/FilterQueryInput.php
tests/Input/FilterQueryInputTest.php

[Input] FilterQuery always show char (not token)

---

.travis.yml
composer.json
tests/Input/XmlInputTest.php
tests/SearchConditionSerializerTest.php

Symfony 3 support

---

.travis.yml
tests/Extension/Core/Type/ChoiceTypeTest.php

Fix PHP 7 compatibility

---

UPGRADE.md
src/SearchConditionInterface.php
src/Value/Compare.php
src/Value/ExcludedRange.php
src/Value/InvalidValue.php
src/Value/PatternMatch.php
src/Value/Range.php
src/Value/SingleValue.php
src/Value/ValueHolder.php
src/ValuesBag.php
src/ValuesBagBuilder.php
src/ValuesError.php
tests/ValuesBagTest.php

Introduce a new API for ValuesBag

---

.travis.yml
README.md
composer.json

Drop support for older php versions

---

src/FieldConfigInterface.php
src/SearchField.php
tests/Extension/Core/Type/IntegerTypeTest.php
tests/Extension/Core/Type/MoneyTypeTest.php
tests/SearchFieldTest.php

- `SearchField::setDataLocked() -> finalizeConfig()`
- `FieldConfigInterface::getDataLocked() -> isConfigLocked()`

Rename FieldConfig locking methods

---

src/ConditionOptimizer/ValuesToRange.php
tests/ConditionOptimizer/ValuesToRangeTest.php

The optimizer failed to optimize other connected value-lists and only optimized the first one.

Fix ValuesToRange ConditionOptimizer

---

.travis.yml
README.md

- Enable coverage report
- Disable xdebug for composer
- Remove old (unneeded) configuration stuff
- Use phpdbg for testing and coverage

Improve TravisCI configuration

---

src/ConditionOptimizer/ChainOptimizer.php
src/SearchFactory.php
src/SearchFactoryBuilder.php
src/SearchFactoryInterface.php

Add `optimizeCondition` to the SearchFactoryInterface to reduce the bootstrapping
process. When nu optimizer is provided the ChainLoader with build-in optimizers is used.

Add SearchFactoryInterface::optimizeCondition()

---

src/Exception/InputProcessorException.php

The InputProcessorException allowed to format an error message, but this got superseded by a better error-handling system and thus this old code is no longer needed.

Fix broken formatting in InputProcessorException

---

src/Exporter/StringQueryExporter.php
src/Input/StringQueryInput.php
tests/Exporter/StringQueryExporterTest.php

* Use spaces between operators for better readability
* Update quoting requirements to reduce unnecessary quoting

Update the StringQuery exported format

---

src/Exporter/ArrayExporter.php
src/Exporter/JsonExporter.php
src/Exporter/StringQueryExporter.php
src/Exporter/XmlExporter.php
src/Input/ArrayInput.php
src/Input/JsonInput.php
src/Input/StringQueryInput.php
src/Input/XmlInput.php

These classes should not be extended.

Make InputProcessors and ConditionExporters final

---

src/Input/StringQueryInput.php
src/Input/XmlInput.php

Remove dead code

---

.travis.yml
composer.json
phpunit.xml.dist
src/Test/FieldTransformationAssertion.php
tests/Extension/Core/ChoiceList/LazyChoiceListTest.php
tests/assertDateTimeEqualsTrait.php

Phpunit update

---

phpunit.xml.dist
src/Test/FieldTransformationAssertion.php
tests/ConditionOptimizer/ChainOptimizerTest.php
tests/Extension/Core/Type/ChoiceTypeTest.php
tests/Extension/Core/Type/CountryTypeTest.php
tests/Extension/Core/Type/IntegerTypeTest.php

Make all tests work with strict-mode

---

src/SearchConditionBuilder.php
src/Test/SearchIntegrationTestCase.php
src/Value/ValuesBag.php
src/ValuesBagBuilder.php
tests/ConditionOptimizer/DuplicateRemoverTest.php
tests/ConditionOptimizer/RangeOptimizerTest.php
tests/ConditionOptimizer/ValuesToRangeTest.php

| Fixed tickets | Closes #155 

155 make searchconditionbuilder strip out parent references when completing

---

.travis.yml

Enable coverage (again)

---

.php_cs
.travis.yml
composer.json
phpunit.xml.dist
tests/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformerTest.php

| BC breaks?    | yes/no
_Updated ICU related tests (time zones are translated, unless there is no localization available)._

Fix Symfony 4 compatibility

---

lib/Elasticsearch/Extension/Conversion/DateConversion.php
lib/Elasticsearch/QueryConditionGenerator.php
lib/Elasticsearch/Tests/Functional/ConditionGeneratorResultsTest.php

[Elasticsearch] Fix Date comparison queries

---

lib/Elasticsearch/Extension/Conversion/DateConversion.php
lib/Elasticsearch/Extension/Conversion/DateTimeConversion.php
lib/Elasticsearch/Extension/ElasticsearchExtension.php
lib/Elasticsearch/Extension/Type/DateTimeTypeExtension.php
lib/Elasticsearch/Tests/Functional/ConditionGeneratorResultsTest.php
lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php

[Elasticsearch] Datetime support

---

Makefile
docker-compose.yaml
lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php

Streamline Docker-Compose for all services

---

lib/Doctrine/Dbal/Query/QueryGenerator.php
lib/Doctrine/Dbal/SqlConditionGenerator.php
lib/Doctrine/Dbal/Tests/Functional/SqlConditionGeneratorResultsTest.php
lib/Doctrine/Dbal/Tests/SqlConditionGeneratorTest.php
lib/Doctrine/Dbal/composer.json
lib/Doctrine/Orm/DqlConditionGenerator.php
lib/Doctrine/Orm/NativeQueryConditionGenerator.php
lib/Doctrine/Orm/Tests/ConditionGeneratorResultsTestCase.php
lib/Doctrine/Orm/Tests/DqlConditionGeneratorTest.php
lib/Doctrine/Orm/Tests/NativeQueryConditionGeneratorTest.php
lib/Doctrine/Orm/composer.json

| Fixed tickets | Related to #182 
PreConditon processing for the Doctrine DBAL and ORM integration.

[Doctrine] pre-condition processing

---

lib/Core/Test/SearchIntegrationTestCase.php
lib/Elasticsearch/QueryConditionGenerator.php
lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php

| Fixed tickets | #210 
| Doc PR        | N/A?

[Elasticsearch] support for setting preconditions

---

lib/Core/Input/CachingInputProcessor.php
lib/Core/SearchCondition.php
lib/Core/Tests/Input/CachingInputProcessorTest.php
lib/Core/Tests/Mock/EmptyInputProcessorStub.php
lib/Core/Tests/Mock/FieldSetStub.php
lib/Core/Tests/Mock/SpyingInputProcessor.php
lib/Core/Tests/Mock/StubInputProcessor.php

[Core] Add CachingInputProcessor for caching input

---

UPGRADE-2.0.md
lib/ApiPlatform/EventListener/SearchConditionListener.php
lib/ApiPlatform/Tests/EventListener/SearchConditionListenerTest.php
lib/Symfony/SearchBundle/Tests/Functional/ApiPlatformTest.php

This was previously deprecated in #228

[ApiPlatform] Remove support for Array input

---

lib/Core/Input/StringInput.php
lib/Core/Tests/Input/StringQueryInputTest.php

[Core] Fix StringQuery group-logical at first pos

---

lib/Elasticsearch/FieldMapping.php
lib/Elasticsearch/QueryConditionGenerator.php
lib/Elasticsearch/Tests/Functional/ConditionGeneratorResultsTest.php
lib/Elasticsearch/Tests/Functional/FunctionalElasticsearchTestCase.php
lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php

[Elasticsearch] has_child support

---

lib/ApiPlatform/Serializer/InvalidSearchConditionNormalizer.php
lib/ApiPlatform/Tests/InvalidSearchConditionNormalizerTest.php
lib/Symfony/SearchBundle/Resources/config/api_platform.xml
lib/Symfony/SearchBundle/Tests/Functional/ApiPlatformTest.php
lib/Symfony/SearchBundle/Tests/Functional/FunctionalTestCase.php

| Fixed tickets | #250 
Closes #250.

fix: normalize invalid search exceptions outside JSON-LD context

---

lib/ApiPlatform/Tests/Mock/FieldSetStub.php
lib/Core/Extension/Core/DataTransformer/OrderTransformer.php
lib/Core/Field/GenericResolvedFieldType.php
lib/Core/Field/OrderField.php
lib/Core/Field/OrderFieldType.php
lib/Core/FieldSet.php
lib/Core/GenericFieldSet.php
lib/Core/Input/ConditionStructureBuilder.php
lib/Core/Input/JsonInput.php
lib/Core/Input/NormStringQueryInput.php
lib/Core/Input/OrderStructureBuilder.php
lib/Core/Input/StringInput.php
lib/Core/Input/StringLexer.php
lib/Core/Input/StringQueryInput.php
lib/Core/SearchCondition.php
lib/Core/SearchOrder.php
lib/Core/SearchPrimaryCondition.php
lib/Core/StructureBuilder.php
lib/Core/Tests/Field/OrderFieldTest.php
lib/Core/Tests/Input/InputProcessorTestCase.php
lib/Core/Tests/Input/JsonInputTest.php
lib/Core/Tests/Input/StringQueryInputTest.php
lib/Core/Tests/Mock/FieldSetStub.php
lib/Doctrine/Dbal/Tests/CachedConditionGeneratorTest.php
lib/Doctrine/Orm/Tests/CachedDqlConditionGeneratorTest.php
lib/Doctrine/Orm/Tests/CachedNativeQueryConditionGeneratorTest.php

| Fixed tickets | #241 
Closes #241.

[Core] order-by support

---

lib/Elasticsearch/QueryConditionGenerator.php
lib/Elasticsearch/Tests/Functional/ConditionGeneratorResultsTest.php
lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php

| Fixed tickets | #259 
Closes #259. Also fixes two other bugs we found while using it.

[Elasticsearch] Fix error handling for unknown mapping, and fix logical condition

---

composer.json
lib/Core/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php
lib/Core/Extension/Core/DataTransformer/NumberToLocalizedStringTransformer.php
lib/Core/Tests/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformerTest.php
lib/Core/composer.json

Data transformer fixes

---

lib/Elasticsearch/QueryConditionGenerator.php
lib/Elasticsearch/Tests/QueryConditionGeneratorTest.php

| Tests pass?   | no
| Fixed tickets | #268 
Follow up to #268 
Current implementation merges only single level nested fields (eg: author[].first_name, author[].last_name), not multiple level ones (item[].author[].name...). 
@dkarlovi Any thoughts how this can be solved? Merging is not working for HAS_CHILD queries with multiple levels as well. 
As this PR solves my current requirement I'm fine with single level fix, but I agree that complete solution is preferred. Unit test covering multiple level nesting case is included but failing... can be removed later.

[Elasticsearch] merge nested queries with the same path

---

.travis.yml
composer.json
lib/ApiPlatform/EventListener/SearchConditionListener.php
lib/ApiPlatform/SearchConditionEvent.php
lib/ApiPlatform/Tests/EventListener/SearchConditionListenerTest.php
lib/ApiPlatform/composer.json
lib/Core/Extension/Core/DataTransformer/MoneyToStringTransformer.php
lib/Core/Extension/Core/Type/CountryType.php
lib/Core/Extension/Core/Type/CurrencyType.php
lib/Core/Extension/Core/Type/LanguageType.php
lib/Core/Extension/Core/Type/LocaleType.php
lib/Core/Input/ConditionStructureBuilder.php
lib/Core/Tests/Extension/Core/DataTransformer/MoneyToStringTransformerTest.php
lib/Core/Tests/Extension/Core/Type/LocaleTypeTest.php
lib/Core/Tests/Input/CachingInputProcessorTest.php
lib/Core/composer.json
lib/Doctrine/Dbal/composer.json
lib/Doctrine/Orm/composer.json
lib/Elasticsearch/composer.json
lib/Symfony/SearchBundle/DependencyInjection/Configuration.php
lib/Symfony/SearchBundle/Resources/config/api_platform.xml
lib/Symfony/SearchBundle/Tests/Functional/SearchProcessorTest.php
lib/Symfony/SearchBundle/composer.json
lib/Symfony/Validator/Tests/InputValidatorTest.php
lib/Symfony/Validator/composer.json

Fix broken tests and deprecation warnings

---

docker-compose.yaml
docker/Dockerfile
lib/Core/Tests/Extension/Core/Type/LanguageTypeTest.php

Localized languages were removed in Intl, this reflects the same changes as done in the Symfony Form component

[Core] Fix failing LanguageTypeTest

---

.github/workflows/ci.yaml

Add GitHub CI workflow configuration

---

.github/workflows/ci.yaml
.gitignore
Makefile
lib/ApiPlatform/Doctrine/Orm/Extension/SearchExtension.php
lib/ApiPlatform/Elasticsearch/Extension/SearchExtension.php
lib/Core/Extension/Core/DataTransformer/LocalizedBirthdayTransformer.php
lib/Core/Tests/Extension/Core/DataTransformer/LocalizedBirthdayTransformerTest.php
lib/Doctrine/Dbal/Query/QueryGenerator.php
lib/Doctrine/Dbal/SqlConditionGenerator.php
lib/Doctrine/Orm/DoctrineOrmFactory.php
lib/Doctrine/Orm/FieldConfigBuilder.php
lib/Elasticsearch/Extension/Conversion/DateConversion.php
lib/Elasticsearch/QueryConditionGenerator.php
phpstan.neon

Phpstan fixes

---

UPGRADE-2.0.md
lib/Core/SearchConditionBuilder.php
lib/Doctrine/Dbal/Query/QueryGenerator.php
lib/Doctrine/Dbal/Tests/Mocks/DatabasePlatformMock.php
lib/Doctrine/Orm/CachedDqlConditionGenerator.php
lib/Doctrine/Orm/CachedNativeQueryConditionGenerator.php

Clean code refactoring

---

lib/Symfony/SearchBundle/DependencyInjection/RollerworksSearchExtension.php

[Bundle] Auto configure interfaces services

---

lib/Core/Exception/TransformationFailedException.php
lib/Core/Input/ConditionStructureBuilder.php
lib/Core/Input/ConditionStructureByViewBuilder.php
lib/Core/Tests/Input/InputProcessorTestCase.php
lib/Core/Tests/Input/JsonInputTest.php
lib/Core/Tests/Input/StringQueryInputTest.php

[Core] TransformationFailedException: Allow custom message to display

---

lib/Core/Tests/Extension/Core/Type/DateTimeTypeTest.php

Fix for Icu version >=73.2

---

lib/Core/Input/CachingInputProcessor.php
lib/Core/Input/ProcessorConfig.php
lib/Core/Tests/Input/CachingInputProcessorTest.php
phpstan-baseline.neon

Fix CachingInputProcessor not using TTL

---

lib/Core/Input/ProcessorConfig.php

[Core] Make ProcessorConfig fluent

---

README.md
lib/Core/Exception/TranslatedArgument.php
lib/Core/Input/ErrorPathTranslator.php
lib/Core/Resources/translations/RollerworksSearch.en.xlf
lib/Core/Resources/translations/RollerworksSearch.nl.xlf
lib/Core/Tests/Input/ErrorPathTranslatorTest.php

[Core] Add ErrorPathTranslator for StringQuery
